version: '3.8'
services:
  db:
    image: postgres:14
    container_name: da-horta-db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: dahorta